default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: gem_turtorial

production:
  <<: *default
  database: fels198_production
  username: fels198
  password: <%= ENV['FELS198_DATABASE_PASSWORD'] %>
